### ISSUE TITLE
Allow inner nested tabs to not set anchors

### ISSUE THREAD

**Issue by dsandber** [spatie/vue-tabs-component#12]
I want to have tabs inside my tabs, but only the outside tabs should set the anchor.

I tried setting href='' on the inside tabs, hoping that would be a cue to not change the anchor, but it didn't work.

I was able to work-around by using jquery to take the href off of the the inner tabs.

It would be nice if setting href='' or a new property "no_anchor=true" would prevent the tab from updating the anchor.

**Comment by dsandber** [comment]
I also tried setting all the inner tab id to be the same as the outer tab name, but that didn't work as all the inner tabs appeared open.

**Comment by dsandber** [comment]
I created a PR for this:

https://github.com/spatie/vue-tabs-component/pull/13

**Comment by freekmurze** [comment]
Conversation continues in #13
