### ISSUE TITLE
Using the library with a <script> tag

### ISSUE THREAD

**Issue by manelclos** [spatie/vue-tabs-component#15]
Hi,

I'm trying to use the library loading it using a <script> tag. First problem is that Tabs and Tab are not exported to the global scope. Second problem is that "vue-tabs" seems not to be a valid name. As a workaround I've changed webpack.config.js to name it "vuetabs" instead:

```
library: 'vuetabs',
```

and use it like:

```
  var Tabs = vuetabs.Tabs;
  var Tab = vuetabs.Tab;

  new Vue({
      components: {
        Tabs,
        Tab
      },
      ...
```

What's the correct way to use it without needed these modifications?

Thanks!

**Comment by pjar** [comment]
I'd love to have that option too since I work on old stack (Rails 3) so have no way of using yarn or npm.

**Comment by sebastiandedeyne** [comment]
I'll look into this together with #17!

**Comment by sebastiandedeyne** [comment]
I'd accept a non-breaking PR to our webpack config that resolves this issue.
