### ISSUE TITLE
Include /dist directory

### ISSUE THREAD

**Issue by pjar** [spatie/vue-tabs-component#17]
We use the old stack (Rails 3) and the only way for us to use these great components is by having .js file to be able to include it in a script tag. 

I can run `npm run build` manually, however, sometimes it is not as straightforward as it should be, npm is npm. I've just spent 1 hour trying to figure out why builds are failing and it turned out that one of the libs became broken: https://github.com/beautify-web/js-beautify/issues/1247

It could be a time saver for me if I could have dist folder already in the repo.

Thanks for your great work! A postcard is coming! :)

**Comment by sebastiandedeyne** [comment]
Gonna consider look into doing this for our packages soon, I'll keep you posted!

**Comment by sebastiandedeyne** [comment]
This would require a pretty big change in our workflow, we'd preferably need something CI-ish for this. Unless there are lots of people asking for this, we're gonna hold off on this for now.

I don't know if this would help in your case, but you can fetch the dist code from unpkg if you need a direct link.

https://unpkg.com/vue-tabs-component@1.4.0/dist/index.js
