### ISSUE TITLE
Inject Icons on the tab controls

### ISSUE THREAD

**Issue by claide** [spatie/vue-tabs-component#18]
Hi, I wonder how to add or customize the `li anchor` tags to have an icon or images. Is it possible to have an option like below?

```
<tab name="First tab" :icon="my-icon"> // custom icon only
<tab name="First tab" :image="src/to/icon"> // image only
<tab name="First tab" :image="src/to/icon" name="First tab"> // image with icon
```

Would love to have like this kind of option. 
Thanks man!

**Comment by freekmurze** [comment]
You can do that using the `prefix` prop. Take a look at [our demo page](http://vue-tabs-component.spatie.be/) (last tab)
