### ISSUE TITLE
Starting point css

### ISSUE THREAD

**Issue by manelclos** [spatie/vue-tabs-component#20]
When using vue-tabs-component, I copied the CSS form the example webpage and modified it to suit my needs. I was wondering if there is any official CSS that is shipped as a base for users to modify.

We had to move "list-style: none" into a more specific selector to be able to use it within Django admin. But I can't find any css code other than the one in docs folder, which is not referenced in the README, so no PR :)

```
.tabs-component-tabs {
  border: solid 1px #ddd;
  /*list-style: none;*/
  border-radius:  6px;
  margin-bottom: 5px;
}

.tabs-component-tabs li {
  list-style: none;
}
```

**Comment by willemvb** [comment]
Thanks for the suggestions! Tweaked it a little and added the CSS reference to the README.
