### ISSUE TITLE
Javascript error if useUrlFragment not specified

### ISSUE THREAD

**Issue by jdooley511** [spatie/vue-tabs-component#22]
Hey there,

I'm not sure if it's intentional to require useUrlFragment to be specified or not, but if I do not specify anything, I get Javascript errors in the console anytime I click a tab:

`Uncaught TypeError: Cannot read property 'useUrlFragment' of undefined at VueComponent.selectTab `

If I specify it, everything works fine.
`<tabs cache-lifetime="120" :options="{ useUrlFragment: false }">`
and
`<tabs cache-lifetime="120" :options="{ useUrlFragment: true }">`

both work fine.

**Comment by freekmurze** [comment]
This is fixed in `1.2.2`
