### ISSUE TITLE
fix unset options prop issues is still an issue

### ISSUE THREAD

**Issue by mnebus** [spatie/vue-tabs-component#23]
the default() for options needs to return an object.

change this:
options: {
                type: Object,
                required: false,
                **default () {
                    useUrlFragment: true
                },**
},

to this:
options: {
                type: Object,
                required: false,
                **default () {
                   return {  useUrlFragment: true }
                },**
},

**Comment by manelclos** [comment]
Exactly as I tested and proposed: https://github.com/spatie/vue-tabs-component/pull/19
+1

**Comment by sebastiandedeyne** [comment]
Fixed in `1.3.0`
