### ISSUE TITLE
pluggable storage

### ISSUE THREAD

**Issue by kmohrf** [spatie/vue-tabs-component#26]
hey,

thanks for working on this :). It would be nice if the storage backend would be pluggable and could be replaced. the expiringStorage is probably a good fit for easier setups but in my case I’d like to control which tab is displayed. apart from that this would also open up the possibility to prevent tab changes. 

i will probably start working on this today and if you’d like to have this feature I’ll prepare a pull request.

**Comment by freekmurze** [comment]
Answered in #28
