### ISSUE TITLE
Create tabs in runtime with vue-router

### ISSUE THREAD

**Issue by farnetani** [spatie/vue-tabs-component#34]
I'm wanting to make when the user chooses a left-side option to be created at the runtime rendering location (`<router-view></router-view>`) a tab containing the component of the route that he selected. It is possible? Do you have any examples? Does Component work well with vue-router?

**Comment by cristijora** [comment]
@farnetani for a vue-router approach I'd recommend doing it without a component as it's more flexible
https://codesandbox.io/s/m3v85m5o2j

Starting from there you could dynamically render the tabs in a list, add more on click and so on.

**Comment by sebastiandedeyne** [comment]
I haven't used this component together with Vue router yet so can't really say if there are pitfalls.

Feel free to share your findings here, or open a specific issue if you encounter any bugs :)
