### ISSUE TITLE
Component not working properly in IE

### ISSUE THREAD

**Issue by krystalcampioni** [spatie/vue-tabs-component#38]
First of all, thanks a lot for the awesome component!

I've noticed that the component doesn't work properly in IE. I know it's kind of a pain to support IE 11 and I don't know if it is on the roadmap for your project, but for the project that I'm currently working on IE is still almost 12% of the visits :/

<img width="889" alt="screen shot 2017-11-23 at 10 00 36" src="https://user-images.githubusercontent.com/4037781/33165499-6c9ae428-d037-11e7-8dc4-271a957ac3f8.png">

I'll try to see if I can solve it, and if I do I can submit a PR if you guys are interested in supporting IE.

Cheers!

**Comment by sebastiandedeyne** [comment]
You can solve this issue by adding an `Array.find` polyfill to your bundle :)

**Comment by krystalcampioni** [comment]
thanks, @sebastiandedeyne I'll do that :)

**Comment by volkova-annie** [comment]
@sebastiandedeyne Could you please explain, what do you mean "adding an Array.find polyfill to your bundle"?
Where should I add it?

**Comment by krystalcampioni** [comment]
@volkova-annie you can either use just the array find polyfill, as here: https://www.npmjs.com/package/array.find-polyfill

or if you prefer you can use babel-polyfill that comes with some other useful polyfills: https://babeljs.io/docs/usage/polyfill/#installation

basically just:
`npm install --save babel-polyfill`

then in your webpack.config
`import "babel-polyfill";`

and include it to your app entry point:
`entry: ["babel-polyfill", "./app/js"]`

**Comment by volkova-annie** [comment]
@krystalcampioni Thanks a lot :)
