### ISSUE TITLE
disable turbolinks

### ISSUE THREAD

**Issue by nPaul** [spatie/vue-tabs-component#41]
Please add data-turbolinks=false on tab links.
On Rails application with turbolinks had bugs, page alwayse reloading when click on tab.

**Comment by sebastiandedeyne** [comment]
We're not going to add this by default to the library as we don't want to maintain stuff that's tightly coupled to a third party.

You could disable Turbolinks on the entire component by adding it to the top level.

```
<tabs data-turbolinks="false">
    <!-- ... -->
</tabs>
```

If we can add a generic prop or something similar to make this easier we're open to extending the package, as long as it's not tied to a specific implementation.
