### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by jpvicari** [spatie/vue-tabs-component#42]
I'm having some trouble building locally and noticed some missing packages, I've added a few but haven't been able to determine all of them. What are all the dependencies? I'd be happy to add them and issue a pull request.

**Comment by sebastiandedeyne** [comment]
Could you be more specific? What was missing? As far as I know, `package.json`'s contents are correct.

**Comment by jpvicari** [comment]
webpack-dev-server was missing, as well as a few babel-plugin's

I was having a few other issues resolving paths, but I believe that was due to the test environment I was working in. I was able to start the project locally, so I'm good moving forward testing a few new features.

Thanks!

**Comment by sebastiandedeyne** [comment]
Thanks for the heads up! Looking into this.
