### ISSUE TITLE
Set active tab on load

### ISSUE THREAD

**Issue by jzatt** [spatie/vue-tabs-component#46]
I've been trying to figure out if there is a way to set what tab should be active on load in the template? I know that you can set it with the url fragment, but it doesn't really fit my use case.

Something like the code to disable a tab `is-disabled="true"` for example; `is-active="true"`

    <tab name="First tab">
        First tab content
    </tab>
    <tab name="Second tab" :is-active="true">
        Second tab content
    </tab>
    <tab name="Third tab">
        Third tab content
    </tab>

Or is there any other way to solve the same behavior?

**Comment by sebastiandedeyne** [comment]
Sorry, this currently isn't supported by this library.
