### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Meenakshise** [spatie/vue-tabs-component#47]
After cloning the npm install is failing 
![image](https://user-images.githubusercontent.com/5516586/35860910-df451f9c-0b6b-11e8-8b01-f7481975aee5.png)

**Comment by sebastiandedeyne** [comment]
What npm version are you on?

**Comment by sebastiandedeyne** [comment]
I think this has something to do with npm's recent `prepublish` script changes, build script will need to be updated.

**Comment by Meenakshise** [comment]
thanks for the reply. I got some other sample to test it. It worked for me..

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy.
