### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by kfirba** [spatie/vue-tabs-component#49]
Hey.

I was playing around with this package and tried to get some nice transition for the tab’s content. Unfortunately, I couldn’t get it to work. I suspect that that we need to do is to wrap the actual code in the `tab.vue` file in a `<transition>` element which then we can define the appropriate classes for the transition itself.

Maybe what we can do is to accept a transition name as a prop of the `<tab>` element and wrap the whole component in a transition element.

Maybe there is a better way of doing it that I’m not aware of?

**Comment by yumyo** [comment]
Is there any progress or plan about this? 
While not ideal, I will be happy even just with a class on the active panel as already available on the active tab.

**Comment by sebastiandedeyne** [comment]
Transitions currently aren't supported, but we'll keep this in mind in a possible next major version
