### ISSUE TITLE
Changing url on tab selection

### ISSUE THREAD

**Issue by drkhunter** [spatie/vue-tabs-component#51]
I'm trying to come up with a way of changing the url when selecting one of the tabs.  So instead of a url fragment `example.com/home#tab1`, it would be `example.com/home/tab1`.  Is this something which could be worked into the component?

**Comment by JBtje** [comment]
You can use `<tabs @changed="tabChanged">` to catch the tab-change event, and update the URL yourself in the method tabChanged, using `router.replace(location)`

do note that the @changed event is emitted once after rendering, allowing you to set the URL accordingly.

@spatie: perhaps add a note for the @changed event in the documentation

**Comment by drkhunter** [comment]
Awesome, thank you.
