### ISSUE TITLE
Working with axios

### ISSUE THREAD

**Issue by reikaP** [spatie/vue-tabs-component#52]
How to working active tabs with axios? tried to implement to alphabetical pagination but i don't have any idea even didn't have any documentation to work with script tag.

**Comment by JBtje** [comment]
Not sure what you're asking, but with `<tabs @changed="tabChanged">` you can trigger your own method (in this case `tabChanged`). The event sends the tab component, so
```
methods: {
  tabChanged( tabComponent ){
    console.log( tabComponent.tab.name )
  }
}
```
with that code you can grab the tab name, and load data via axios on request.
