### ISSUE TITLE
is possible to get the events a tab will emit - need to know a different tab was clicked

### ISSUE THREAD

**Issue by jfabiani** [spatie/vue-tabs-component#54]
When my users click on a tab that is not active I need a way to do a few things before leaving the active tab content.  Is that possible????  Is there a before_change???
In my situation - if the edit mode is active I need to de-activate the edit mode and cancel any updates.

**Comment by jillztom** [comment]
yeah this `beforeChange` would be nice to have!

**Comment by sebastiandedeyne** [comment]
Gonna hold off on this, might as well listen to the `changed` event in this case. I might reconsider this in a next major version.
