### ISSUE TITLE
Tabs have no CSS

### ISSUE THREAD

**Issue by pzjzeason** [spatie/vue-tabs-component#58]
**I'm new with Vue and Vue cli. I'd like to try out this tabs-component, and my code in App.vue is as follows:**
```
<template>
  <div>
    <tabs>
        <tab name="First tab">
            First tab content
        </tab>
        <tab name="Second tab">
            Second tab content
        </tab>
        <tab name="Third tab">
            Third tab content
        </tab>
    </tabs>
  </div>
</template>

<script>
import Vue from 'vue';
import {Tabs, Tab} from 'vue-tabs-component';
Vue.component('tabs', Tabs);
Vue.component('tab', Tab);
export default {
  name: 'App'
}
</script>
```
In browser:
![image](https://user-images.githubusercontent.com/36041376/39308912-4958bb94-4999-11e8-811d-1495fa66813e.png)

**What can I do to fix it, please show me the way!**

**Comment by karam94** [comment]
You have to manually put the CSS in yourself.

https://github.com/spatie/vue-tabs-component/blob/master/docs/resources/tabs-component.css

Good luck!

**Comment by mkosir** [comment]
pzjzeason, add a following line into your component script:
import 'vue-tabs-component/docs/resources/tabs-component.css';
This will addd default styling to the component.
