### ISSUE TITLE
page scroll to top when click change tab

### ISSUE THREAD

**Issue by hoangnguyen291** [spatie/vue-tabs-component#60]
when I click to another tab, page is scrolling to top, this is very annoying

**Comment by sebastiandedeyne** [comment]
Could you share your code so we can see what's going wrong? Normally this should be prevented.

Gonna close this since it's an older issue and I'm cleaning up the repository a bit. But please open a new issue with some more details if there's still a problem!

**Comment by swaminator** [comment]
I have the same issue. I'm using the https://github.com/pskordilakis/vuepress-tabs and the page scrolls to the top automatically. This happens randomly not just when I click on a new tab.
