### ISSUE TITLE
Error in IE11 - Object doesn't support property or method 'find'

### ISSUE THREAD

**Issue by hicksben359** [spatie/vue-tabs-component#62]
Couldn't see a mention of which browsers are supported in the docs but I'm getting an error in IE11 - on your demo page it's coming in at line 11214 of app.js and is _Object doesn't support property or method 'find'_

Any chance of a fix?

**Comment by boomhq** [comment]
Look #38

**Comment by sebastiandedeyne** [comment]
Not going to fix this, there are a few `find` polyfill out there, add one of those to your application's bundle.
