### ISSUE TITLE
How do I conditionally set a tab visibility false using setTabVisible method

### ISSUE THREAD

**Issue by ian-pinto-vamaship** [spatie/vue-tabs-component#63]
How do I conditionally set a tab visibility false using setTabVisible method. I need hide/unhide certain tabs conditionally.

**Comment by JBtje** [comment]
**Note: why isn't is-visible a prop?**

```html
<tab name="Invissible tab" v-if="tabXvisible">
...
</tab>
```
```js
export default {
    data() {
        return{
            tabXvisible = false,
        }
    }
}
```

or you can do it programically:
```js
this.$children[0].findTab('#advice').isVisible = false
```
but that is not the way vue is intended to work...

**Comment by manelclos** [comment]
Hi @ian-pinto-vamaship,

You can watch the variable to automate it, reusing @JBtje data ():

```html
<tabs ref="tabs">
  ...
</tabs>
```

```javascript
  ...
  watch: {
    tabXvisible: function (val) {
      this.$refs.tabs.setTabVisible(this.tabXHash, val)
    }
  }
  ...
```

@JBtje I see no reason why isVisible could not be a property, PR? :)

**Comment by JBtje** [comment]
@manelclos PR is only useful if the project owner accepts them.... Seems that's not the case for this project. (my PR is still not accepted)

**Comment by manelclos** [comment]
@JBtje as you can see here https://github.com/spatie/vue-tabs-component/pull/67#issuecomment-417677592 you just need to be patient

**Comment by sebastiandedeyne** [comment]
The visibility method was added to work a round a specific case (see https://github.com/spatie/vue-tabs-component/pull/16).

In hindsight, it should have been done differently, but we don't really want to support any new configuration at the moment, so we're going to stick with the existing API.

We'll revisit this problem in a future major version of this package.
