### ISSUE TITLE
Can't import vue-tabs-component

### ISSUE THREAD

**Issue by nick-dolan** [spatie/vue-tabs-component#65]
Hello, when I'm trying to import library: `import Tabs from 'vue-tabs-component';`
I see, Error: Cannot find module '../expiringStorage' from ...
What could be the problem?

**Comment by Preen** [comment]
+1

**Comment by joshuacurtiss** [comment]
+1

Using Browserify, Vueify, and Babelify.  If that gives a hint.  Bummer, this component is dead in the water if it won't compile in my project.

**Comment by sebastiandedeyne** [comment]
I have no experience with module resolution in browserify. Can anyone tell me what causes this?

**Comment by joshuacurtiss** [comment]
I wish I knew more about it.  I googled a bit and found this interesting bit: 
https://github.com/browserify/browserify/issues/1310#issuecomment-113143686

Appears it could be addressed with this tweak to the Browserify config. But I haven't had time to test this out.

**Comment by JonathanBesson** [comment]
Hello, someone has a result about this bug ? i'm on it and i'm stuck on it ... 

> `[17:03:30] gulp-notify: [Compile Error] Error: Cannot find module './components/Tabs' from [localpath]\client\node_modules\vue-tabs-component\dist'`

> `[17:03:30] gulp-notify: [Compile Error] Error: Cannot find module './components/Tab' from '[localpath]\client\node_modules\vue-tabs-component\dist'`

> `[17:03:30] gulp-notify: [Compile Error] Error: Cannot find module '../expiringStorage' from '[localpath]\client\node_modules\vue-tabs-component\dist'`

I'm using browserify, but i'm a newbies of that ... if anyone has an idea.

thanks a lot, bests regards all

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy.
