### ISSUE TITLE
Typescript Support (Feature Request)

### ISSUE THREAD

**Issue by lee-alderdice** [spatie/vue-tabs-component#66]
Hi,

Would you be able to add Typescript support into your next release.  The code below creates a 'No declaration file ...' error and the same applies for global import into main.ts.

```
<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import Tabs from 'vue-tabs-component';

@Component
export default class InitialSetupWizard extends Vue {
  @Prop() private msg!: string;
}
</script>
```

Many thanks,
Lee

**Comment by sebastiandedeyne** [comment]
Sorry, we're not planning to maintain a type declaration file at the moment. I sugges you declare the minimum necessary typings in your own application.
