### ISSUE TITLE
abilty to set default tab when none specified

### ISSUE THREAD

**Issue by dissolve** [spatie/vue-tabs-component#69]
It would be nice to specify that if there is no other reason to select a tab, don't just assume tab[0] but rather have an additional option that can pass the ID or the index perhaps of the tab to default to.

It would just need an additional option above this line 
https://github.com/spatie/vue-tabs-component/blob/master/src/components/Tabs.vue#L76

**Comment by dissolve** [comment]
To explain a little more, this is useful when you disable the tab cache.

**Comment by sebastiandedeyne** [comment]
PR merged!
