### ISSUE TITLE
Change tab programmatically 

### ISSUE THREAD

**Issue by umar13893** [spatie/vue-tabs-component#71]
Hello. Thanks for great package. Is it possible to change the tab programmatically by clicking on a link or button? thank you!

**Comment by thexpand** [comment]
I've tried with an anchor, pointing to the correct hash, but it does not work.
Also, I've tried creating an anchor with `aria-controls` with a value, equal to the tab name and `role="tab"`, but it does not work either. Apparently, such functionality does not exist.
Any solutions/workarounds?

**Comment by mannyyang** [comment]
Haven't tried it in code, but you could probably set a ref on the Tabs component and with that reference have access to use the internal selectTab() method that the tab component uses on its click event.

**Comment by sebastiandedeyne** [comment]
At the moment I recommend using @mannyyang's solution, and call the internal `selectTab` method through a ref.
