### ISSUE TITLE
Tabs get [__ob__: Observer]

### ISSUE THREAD

**Issue by romanmarkelov** [spatie/vue-tabs-component#74]
Hi, there! I created a some component  and extended at a vue-tabs-component and I have following behavior: my component 50/50 initialize with bugs on [78 number of string](https://github.com/spatie/vue-tabs-component/blob/master/src/components/Tabs.vue#L75) it get  [__ob__: Observer]  array and does not pass the condition

<details><summary>MyComponent</summary>

```vue
<template>
  <div
    v-if="!isMobile"
    class="tabs-component"
  >
    <ul
      role="tablist"
      class="tabs-component-tabs stack"
    >
      <li
        v-for="(tab, i) in tabs"
        v-show="tab.isVisible"
        :key="i"
        :class="{ 'is-active': tab.isActive, 'is-disabled': tab.isDisabled }"
        class="tabs-component-tab"
        role="presentation"
      >
        <a
          :aria-controls="tab.hash"
          :aria-selected="tab.isActive"
          :href="tab.hash"
          class="tabs-component-tab-a"
          role="tab"
          @click="selectTab(tab.hash, $event)"
        >
          <span class="tabs-component-tab-text">{{ tab.header }}</span>
        </a>
      </li>
    </ul>
    <div class="tabs-component-panels">
      <slot/>
    </div>
  </div>
  <Collapse
    v-else
    v-model="activeNames"
  >
    <slot/>
  </Collapse>
</template>


<script>
import { Vue, Component } from 'vue-property-decorator';
import { Collapse } from 'element-ui';
import { Tabs } from 'vue-tabs-component';
import mobileDetector from '@/mobileDetector';

@Component({
  extends: Tabs,
  components: { Collapse },
  mixins: [mobileDetector]
})
export default class MyComponent extends Vue {}
</script>
```

```js
export default {
  data: () => ({
    isMobile:
      Math.max(document.documentElement.clientWidth, window.innerWidth || 0) <
      768
  })
};
```

</details>

**Comment by sebastiandedeyne** [comment]
Sorry, but I don't fully understand this issue. What error message are you seeing? Or how is the package behaving wrong?

**Comment by romanmarkelov** [comment]
First (active) tab not initialise. I not get any errors or warnings. 

I debug and see the cause
```this.tabs =   [__ob__: Observer] ```

For this cause not passed condition below
```js
            if (this.tabs.length) {
                this.selectTab(this.tabs[0].hash);
            }
```

But sometimes MyComponent initialise without troubles

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy.
