### ISSUE TITLE
Multiple Tabs in a components

### ISSUE THREAD

**Issue by RALLYLANA** [spatie/vue-tabs-component#75]
I everyone, i create a component that contains 2 or more group of tabs.
So when I click on a tab every other tabs changes their contents. How do I separate the operation of the tabs, so that everyone is independent??

Thanks a lot for every suggestion.

**Comment by suits-at** [comment]
Try disabling the urlFragment via the options [see Documentation here](https://github.com/spatie/vue-tabs-component#disable-modifying-the-url-fragment ).

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy.
