### ISSUE TITLE
1.5.0 is missing

### ISSUE THREAD

**Issue by dariuszwisniewski** [spatie/vue-tabs-component#76]
As in the title the newest version of code isn't tagged. Could you please provide some details on when is it going to be available?

**Comment by sebastiandedeyne** [comment]
Was going to release this week but didn't find the time, expect it early next week :)

**Comment by dariuszwisniewski** [comment]
That would be perfect, thank you! :)

**Comment by dariuszwisniewski** [comment]
@sebastiandedeyne any updates on that ? I think I'll have to implement a workaround for now as I can't wait any longer :) Cheers

**Comment by sebastiandedeyne** [comment]
Published!
