### ISSUE TITLE
Page scrolls to the top randomly

### ISSUE THREAD

**Issue by swaminator** [spatie/vue-tabs-component#78]
I'm using: https://github.com/pskordilakis/vuepress-tabs which integrates tabs with my Vuepress project. I've got it working, however I run into issues where as I scroll the page randomly jumps to the top. It is not 100% reproducible unfortunately but happens pretty regularly (about once every 10 scrolls)

**Comment by controlla-io** [comment]
Not sure if this is related, but on my installation when I click the tab it works fine, but a second click makes the screen scroll down to the top of the tab content (this might almost be a feature - is that the case?)

**Comment by XGhozt** [comment]
Can confirm. No page scrolling should happen at all when a tab is clicked.

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy.
