### ISSUE TITLE
Moving prefix and suffix to slot

### ISSUE THREAD

**Issue by spyric** [spatie/vue-tabs-component#8]
Hello. Thanks for great package. But I want to offer you to move prefix and suffix content to slots. Since it can have HTML and become a bit complicated to handle dynamic things like counters.

If you like the idea I can take care about implementing it

**Comment by sebastiandedeyne** [comment]
Hi! We really like the idea, we even tried to do it ourselves at some point: #6

There are some hurdles in the implementation to get slots to work here. Feel free to play around and if you're able to find a solution to get everything to work, send a PR.

Please ensure that passing them as props also still work if you'd do this.
