### ISSUE TITLE
Doesn't work with vue-router

### ISSUE THREAD

**Issue by visualcookie** [spatie/vue-tabs-component#9]
When using vue-router, I can't access the tabs anymore.

**Comment by sebastiandedeyne** [comment]
What do you mean by "can't access the tabs anymore"? Could you provide some steps (and code) on how to reproduce this issue?

**Comment by visualcookie** [comment]
Sure. What happens is that when I click on a tab, he screws up the router entirely (e.g. removes /#/) and doesn't even navigate to the clicked tab. You can easily test it by using `vue-cli` and create a new webpack based project. (Codesamples from it below)

**main.js**:
``` javascript
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import {Tabs, Tab} from 'vue-tabs-component'
import App from './App'
import router from './router'

Vue.config.productionTip = false

Vue.component('tabs', Tabs)
Vue.component('tab', Tab)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})
```

**components/Home.vue**:
``` vue
<template>
  <div>
    <h1>Homepage</h1>
    <tabs>
        <tab name="First tab">
            First tab content
        </tab>
        <tab name="Second tab">
            Second tab content
        </tab>
        <tab name="Third tab">
            Third tab content
        </tab>
    </tabs>
  </div>
</template>
```

**router/index.js**:
``` javascript
import Vue from 'vue'
import Router from 'vue-router'
import Home from '@/components/Home'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'Home',
      component: Home
    }
  ]
})
```

**Comment by visualcookie** [comment]
Also here's a video example of it: http://recordit.co/OlJbVjBaYT

**Comment by sebastiandedeyne** [comment]
Hmm, this is because the tabs use a hash to store the active tab in the url as fragment. We'd need an option to disable this for this to be used with vue-router (this package wasn't made with vue-router in mind, more for static sites that need a few sprinkles of dynamic components).

I'll try to look into this soon and see what I can do!

**Comment by visualcookie** [comment]
Yeah, thought about it. If it would also work to have the tabs active on refresh or by url would be a bomb but if URL changing doesn't work with vue-router, I'm also fine with an upcoming solution.

**Comment by Eduardoveras** [comment]
+1, same issue here with vue router

**Comment by mjalindahl** [comment]
+1, same issue as well.

**Comment by freekmurze** [comment]
It might be a while until we get around this. We'd accept a fully tested, non breaking PR that fixes this.

**Comment by meyergre** [comment]
Using `mode: 'history' ` in vue-router's initialization as a workaround works for me

````
export default new Router({
  mode: 'history',
  routes: [
    {
        ...
    }
  ]
})
````

**Comment by digitalit** [comment]
This worked for me.

```
                          <tab id="/#Tab1" name="First tab">
                                First tab content
                            </tab>
                            <tab id="/#Tab2" name="Second tab">
                                Second tab content
                            </tab>
                            <tab id="/#Tab3" name="Third tab">
                                Third tab content
                            </tab>
```

**Comment by manelclos** [comment]
I had the same issue. I've created pull request https://github.com/spatie/vue-tabs-component/pull/14, comments welcomed!

**Comment by freekmurze** [comment]
We'll handle this further in #14
